---
- name: install dependencies
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - tlog
    - cockpit
    - cockpit-session-recording

- name: copy sssd config
  copy:
    src: sssd-session-recording.conf
    dest: /etc/sssd/conf.d/sssd-session-recording.conf
    mode: '0600'

- name: enable cockpit
  systemd:
    name: cockpit.socket
    enabled: yes
    daemon_reload: yes

- name: install journalbeat
  yum:
    name: "https://artifacts.elastic.co/downloads/beats/journalbeat/journalbeat-{{ elastic_version }}-x86_64.rpm" 
    state: present

- name: copy journalbeat config
  template:
    src: journalbeat.yml.j2
    dest: /etc/journalbeat/journalbeat.yml

- name: enable journalbeat
  systemd:
    name: journalbeat.service
    enabled: yes
    daemon_reload: yes

- name: start cockpit
  systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: yes

- name: restart sssd
  systemd:
    name: sssd
    state: restarted
    daemon_reload: yes

- name: start journalbeat
  systemd:
    name: journalbeat.service
    state: restarted
    daemon_reload: yes
